name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test containers (unit tests)
        run: docker-compose -f docker-compose.yaml up --build --abort-on-container-exit

      - name: Run integration tests
        run: docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
